[package]
name = "powerfx-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
log = "0.4.20"
peg = "0.8.1"
time = "0.3.28"
tokio = { version = "1.30.0", features = ["full"] }